config_version = "0"

exclude_patterns = [
  "**/node_modules/**",
  "**/vendor/**",
  "**/cypress/*",
  "**/test/**",
  "**/tests/**",
  "**/vendor/",
]

test_patterns = [
  "**/test/**",
  "**/tests/**",
]

[smells]
mode = "comment"

[smells.boolean_logic]
threshold = 4

[smells.file_complexity]
threshold = 55

[smells.return_statements]
threshold = 4

[smells.nested_control_flow]
threshold = 4

[smells.function_parameters]
threshold = 4

[smells.function_complexity]
threshold = 5

[smells.duplication]
threshold = 22

[[source]]
name = "default"
default = true

[[plugin]]
name = "php-codesniffer"
package_file = ".qlty/configs/composer.json"